trigger:
- '*'

pool:
  name: CR-LAP-JOS-FAL
  vmImage: 'ubuntu-20.04'

  demands:
  
  - npm

steps:
# Prepare Analysis Configuration task
- task: SonarQubePrepare@5
  inputs:
   
    SonarQube: 'SonarConexion'
    scannerMode: 'MSBuild'
    projectKey: 'Space_Game_-_web_-_Tests_Space_Game_-_web_AYKJrQznFqta1f3xq63W'
    projectName: 'Space Game - web'

# Run Code Analysis task
- task: SonarQubeAnalyze@5

# Publish Quality Gate Result task
- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'